* v3.5.0 - Fix #2   - Fix sample install instructions   - Fix var for quiet upgrade   - Update documentation with 1.4.3 compatibility   - Add additional lsb logging   - Add error codes for `status`, `terminate`, `start`, `stop`, `reload`, `quietupgrade`, `destroy`

diff --git a/nginx b/nginx
--- a/nginx
+++ b/nginx
@@ -25,9 +25,9 @@
 # Author:  Jason Giedymin
 #          <jason.giedymin AT gmail.com>.
 #
-# Version: 3.0 22-APR-2013 jason.giedymin AT gmail.com
+# Version: 3.5.0 11-NOV-2013 jason.giedymin AT gmail.com
 # Notes: nginx init.d dash script for Ubuntu.
-# Tested with: Ubuntu 12.10, nginx-1.3.16
+# Tested with: Ubuntu 13.10, nginx-1.4.3
 # 
 # This script's project home is:
 #   http://github.com/JasonGiedymin/nginx-init-ubuntu
@@ -61,7 +61,15 @@
 #------------------------------------------------------------------------------
 #                               Functions
 #------------------------------------------------------------------------------
-. /lib/lsb/init-functions
+LSB_FUNC=/lib/lsb/init-functions
+
+# Test that init functions exists
+test -r $LSB_FUNC || {
+  echo "$0: Cannot find $LSB_FUNC! Script exiting." 1>&2
+  exit 5
+}
+
+. $LSB_FUNC
 
 #------------------------------------------------------------------------------
 #                               Consts
@@ -90,11 +98,14 @@ NGINX_CONF_FILE="/usr/local/nginx/conf/nginx.conf"
 #                               Simple Tests
 #------------------------------------------------------------------------------
 
-#test if nginx is a file and executable
-test -x $DAEMON || exit 0
+# Test if nginx is a file and executable
+test -x $DAEMON || {
+  echo "$0: You don't have permissions to execute nginx." 1>&2
+  exit 4
+}
 
 # Include nginx defaults if available
-if [ -f /etc/default/nginx ] ; then
+if [ -f /etc/default/nginx ]; then
     . /etc/default/nginx
 fi
 
@@ -172,9 +183,11 @@ status(){
     isAlive=$?
 
     if [ "${isAlive}" -eq $TRUE ]; then
-        echo "$PIDNAME found running with processes:  `pidof $PS`"
+        log_success_msg "$PIDNAME found running with processes:  `pidof $PS`"
+	exit 0
     else
-        echo "$PIDNAME is NOT running."
+        log_warning_msg "$PIDNAME is NOT running."
+	exit 3
     fi
 }
 
@@ -198,13 +211,15 @@ start() {
     isAlive=$?
     
     if [ "${isAlive}" -eq $TRUE ]; then
-        log_end_msg $SCRIPT_ERROR
+        log_warning_msg $SCRIPT_ERROR
+        exit 0
     else
         start-stop-daemon --start --quiet --chuid \
         $RUNAS --pidfile $PIDSPATH/$PIDFILE --exec $DAEMON \
         -- -c $NGINX_CONF_FILE
         setFilePerms
         log_end_msg $SCRIPT_OK
+        exit 0
     fi
 }
 
@@ -220,13 +235,16 @@ stop() {
         wait_for_pid 'removed' $PIDSPATH/$PIDFILE
 
         if [ -n "$try" ] ; then
-            log_end_msg $SCRIPT_ERROR
+            log_failure_msg $SCRIPT_ERROR
+            exit 1
         else
             removePIDFile
             log_end_msg $SCRIPT_OK
+            exit 0
         fi
     else
-        log_end_msg $SCRIPT_ERROR
+        log_warning_msg $SCRIPT_ERROR
+        exit 0
     fi
 }
 
@@ -240,8 +258,10 @@ reload() {
     if [ $? -eq $TRUE ]; then
         `killall -HUP $PS` #to be safe
         log_end_msg $SCRIPT_OK
+        exit 0
     else
-        log_end_msg $SCRIPT_ERROR
+        log_warning_msg $SCRIPT_ERROR
+        exit 7
     fi
 }
 
@@ -264,6 +284,7 @@ quietupgrade() {
             removePIDFile $PIDSPATH/$PIDFILE.oldbin
 
             log_end_msg $SCRIPT_OK
+            exit 0
         else
             log_end_msg $SCRIPT_ERROR
             
@@ -276,10 +297,12 @@ quietupgrade() {
             wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
             removePIDFile $PIDSPATH/$PIDFILE.oldbin
 
-            log_end_msg $SCRIPT_ok
+            log_end_msg $SCRIPT_OK
+            exit 0
         fi
     else
-        log_end_msg $SCRIPT_ERROR
+        log_warning_msg $SCRIPT_ERROR
+        exit 0 # service isn't running, nothing to do
     fi
 }
 
@@ -299,12 +322,14 @@ terminate() {
     done
 
     log_end_msg $SCRIPT_OK
+    exit 0
 }
 
 destroy() {
     log_daemon_msg "Force terminating and may include self (via KILLALL) $DESCRIPTION"
     killall $PS -q >> /dev/null 2>&1
     log_end_msg $SCRIPT_OK
+    exit 0
 }
 
 pidof_daemon() {
@@ -355,8 +380,7 @@ case "$1" in
         FULLPATH=/etc/init.d/$PS
         echo "Usage: $FULLPATH {start|stop|restart|force-reload|status|configtest|quietupgrade|terminate|destroy}"
         echo "       The 'destroy' command should only be used as a last resort." 
-        exit 1
+        exit 3
         ;;
 esac
 
-exit 0
